### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Luryy** [Luryy/GuerreireBot#1]
- [ ] Refactoring
  - [ ] Separete db queries   
- [ ] GuerreireData
  - [ ] Strategic Farois - (color on strtegic plan)
  - [ ]  How Much to Farois - ( answer to achive)
  - [ ] Send data after update fat
- [ ] Guerreire Mail
- [ ] Helpers
  - [ ] 1000.00 to 1.000,00

**Comment by Luryy** [comment]
- [ ] Allow delete ejs
- [ ] Access control
